apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE
  namespace: NAMESPACE
  labels:
    project: akri
    component: webhook
    language: golang
spec:
  replicas: 1
  selector:
    matchLabels:
      project: akri
      component: webhook
  template:
    metadata:
      labels:
        project: akri
        component: webhook
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: webhook
          image: ghcr.io/dazwilkin/akri-webhook@sha256:d4c880cf3d5f32c967d80494b80aadce6fe86f2965aa19cf43eafe18fd9791cd
          imagePullPolicy: Always
          args:
            - --tls-crt-file=/secrets/tls.crt
            - --tls-key-file=/secrets/tls.key
            - --port=8443
            - --logtostderr
            - -v=2
          volumeMounts:
            - name: secrets
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: SERVICE
