apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: SERVICE
  namespace: NAMESPACE
  labels:
    project: akri
    component: validating-webhook
    language: golang
webhooks:
  - name: SERVICE.NAMESPACE.svc
    clientConfig:
      service:
        name: SERVICE
        namespace: NAMESPACE
        port: 443
        path: "/validate" # Matches `main.go#L160`
      caBundle: CABUNDLE
    rules:
      - operations:
          - "CREATE"
          - "UPDATE"
        apiGroups:
          - "*"
        apiVersions:
          - "akri.sh"
        resources:
          - "*"
        scope: "*"
    admissionReviewVersions:
      - v0
      - v1beta1
      - v1
    # namespaceSelector:
    #   matchLabels:
    #     project: akri
    sideEffects: None
